export const circuits_list: { name: string; path: string; description: string; source: string }[] = [
  {
    name: "Bahrain GP - Bahrain International Circuit",
    path: "Bahrain",
    description: "Located in the heart of the Sakhir desert, Bahrain International Circuit is a unique and contemporary facility that is synonymous with the highest levels of global motorsport. Featuring five different track layouts, the circuit first saw life in 2004 when the first ever Formula 1 Grand Prix took place in the country, making it the first-ever track in the Middle East to host the Formula 1 World Championship. Bahrain International Circuit continues to host staggering crowds and a wide range of events and activities, and serves as a platform that encourages motorsports in the country.",
    source: "About Bahrain Internation Circuit, bahraingp.com",
  },
  {
    name: "Azerbaijan GP - Baku City Circuit",
    path: "Baku",
    description: "A mixture of wide and open and tight and twisty. The lonnnnng main straight along the Baku shoreline is a slipstreaming mecca, and with cars able to run three abreast into Turn 1, the action often looks more IndyCar than F1. However from there, the track loops around into the city's narrow, winding Icheri Sheher old town, dramatically wending past Baku's medieval city walls. As in Monaco, slightest mistakes are punished quickly and severely, while set-up wise, the teams are forced to choose between downforce for the twisty bits and less drag for the straight.",
    source: "Azerbaijan Grand Prix, formula1.com",
  },
  {
    name: "Spanish GP - Circuit de Barcelona-Catalunya",
    path: "Barcelona-Catalunya",
    description: "Located just outside of Barcelona, the Circuit de Barcelona-Catalunya was built in 1991 and took over the Spanish Grand Prix the very same year. Many of the world's top race drivers have found themselves atop the podium at the unique circuit, including Michael Schumacher, who won the race a record six times, including four in a row from 2001-2004. The track requires drivers and teams to be on their A game at all times, as wind and weather can dramatically affect the strength of a given setup or tire compound. Barcelona mixes a long, fast front straightaway with flowing curves early in the lap and a number of heavy braking and even blind corners before heading back to the finish line.",
    source: "Circuit de Barcelona-Catalunya, iracing.com",
  },
  {
    name: "United States GP - Circuit of the Americas",
    path: "COTA",
    description: "The Circuit of the Americas, or COTA for short, is a premier motorsports complex nestled on a massive 1,500-acre plot near Austin, Texas. Opened in 2012, the crown jewel of COTA is its 3.4-mile long FIA Grade 1 road course, designed by a dream team consisting of architect Tavo Hellmund, motorcycle legend Kevin Schwantz, and renowned F1 track architect Hermann Tilke. The layout itself is a thrilling mix of iconic corners borrowed from legendary circuits around the world. Take the first section for instance, which pays homage to Silverstone's revered Maggots-Becketts-Chapel complex, a high-speed, multi-corner challenge that demands precision and courage from drivers.",
    source: "Circuit of the Amercias, wikipedia.com",
  },
  {
    name: "Emilia Romagna GP - Autodromo Enzo e Dino Ferrari",
    path: "Emilia-Romagna",
    description: "The Imola Circuit is renowned for its challenging layout, which combines a series of high-speed straights and technical corners. The track spans 4.909 kilometers (3.050 miles) and features 17 turns, demanding precise driving skills and offering little margin for error. Notable sections of the track include the Tamburello corner, Villeneuve chicane, Acque Minerali complex, and the Rivazza turns. These sections are known for their technical difficulty and the physical demands they place on drivers.",
    source: "Navigating the Imola GP Circuit: A Detailed Look, f1worldwide.com",
  },
  {
    name: "Mexico City GP - Autodromo Hermanos Rodriguez",
    path: "Hermanos-Rodriguez",
    description: "The Mexican Grand Prix was first held on 4 November 1962 at the Magdalena Mixhuca circuit. The circuit was the first international racetrack in Mexico, and like Monza in Milan, Italy, it was built within a park in the center part of a major city, in this case the Mexican capital of Mexico City. The race provided unique challenges for racing, standing at 2,240m (7,340 ft) above sea level, as well as the long, 180-degree, lightly banked and fast Peraltada corner that finishes the lap, in addition to being a bumpy racetrack from actively shifting soils beneath the circuit.",
    source: "Mexico Grand Prix, wikipedia.com",
  },
  {
    name: "Hungarian GP - Hungaroring",
    path: "Hungaroring",
    description: "Work began on the Hungaroring in 1985, and the track was race-ready just nine months later. The Hungarian government had originally considered reviving the old Nepliget park circuit in Budapest in a bid to host Formula 1 in the country, but in the end decided to create a purpose-built facility instead. [...] With several series of corners to string together, teams opt for Monaco levels of downforce, with a well-sorted chassis tending to be rewarded over horsepower given the short straights on offer. It's a challenge many of the drivers relish, however, with finding a good rhythm key to setting fast lap times.",
    source: "Hungarian Grand Prix, formula1.com",
  },
  {
    name: "Las Vegas GP - Las Vegas Strip Circuit",
    path: "Las-Vegas",
    description: "The 6.201 km (3.853 mi)[7] street circuit runs counterclockwise and features 17 corners and a 1.9 km (1.2 mi) straight.[8][9] It starts in a former parking lot which had been bought by Formula One for $240 million and developed into the pits and paddock area, and now contains the permanent part of the circuit.[10] The track goes down the Las Vegas Strip.[11] The 1.9 km (1.2 mi) flat-out section with two straights and a slight sweeping left curve goes past some of Las Vegas's most famous hotels and casinos.",
    source: "2023 Las Vegas Grand Prix, wikipedia.com",
  },
  {
    name: "Singapore GP - Marina Bay Street Circuit",
    path: "Marina-Bay",
    description: "The 5.063km Marina Bay Circuit is one of the most physically demanding on the calendar, its bumpy street surface coupled with humid conditions giving the drivers plenty to think about. With 23 corners, they are working the wheel a lot, too, around the high-speed lap - the physical stress causing them to lose as much as 3kg over the course of a race. The circuit also boasts some of the most unique features of any track on the F1 calendar, including Turn 18, which actually sees the drivers pass underneath a grandstand.",
    source: "Singapore - Marina Bay, formula1.com",
  },
  {
    name: "Australian GP - Melbourne GP Circuit",
    path: "Melbourne",
    description: "As a temporary facility, Albert Park can be quite bumpy, while the circuit at the start of the weekend is often slippery, rubbering in as the sessions progress. It's also a circuit that requires a well-sorted chassis, with several spots on the track where the drivers require a reactive front end to allow them to chuck it into a corner - the main one being the rapid Turn 11-12 chicane. Melbourne is also one of the faster tracks on the calendar, with Lewis Hamilton's 2018 pole lap set at an average of 235km/h.",
    source: "Australia - Melbourne, formula1.com",
  },
  {
    name: "Miami GP - Miami International Autodrome",
    path: "Miami",
    description: "Having made its F1 debut in May 2022, the Miami International Autodrome is a temporary circuit, but one designed to have a permanent feel. The 5.41km layout features 19 corners, three straights, three DRS zones, and top speeds of over 340km/h. There are elevation changes too, the main one found between Turns 13 and 16, with the track heading over an exit ramp and under various flyovers across uneven ground. The Turn 14-15 chicane, meanwhile, has an uphill approach, with a crest in the middle, and then drops down on exit.",
    source: "Miami International Autodrome, formula1.com",
  },
  {
    name: "Canadian GP - Circuit Gilles Villeneuve",
    path: "Montreal",
    description: "The fast, low-downforce circuit is one of the drivers' favourites. The track is quite stop-start, with lots of heavy-braking chicanes and the famous hairpin to get the anchors working hard. Out of the corners, though, the track is quick and flowing, while the most iconic piece of the circuit comes right at the end of the lap: the Wall of Champions, so-called after excursions into it from Damon Hill, Jacques Villeneuve and Michael Schumacher during the 1999 Canadian Grand Prix weekend.",
    source: "Canada - Montreal, formula1.com",
  },
  {
    name: "Italian GP - Autodromo Nazionale Monza",
    path: "Monza",
    description: "Monza is a true cathedral to speed, unmatched around the world for its sense of history and passion, fuelled in part by its long history and also the fanaticism of the Italian fans, the tifosi. With the steadily decaying remnants of the high speed banked circuit providing a backdrop through the parkland trees, the atmosphere here is like no other; a mix of speed, melodrama and more than a hint of melancholy. Today, Monza retains its popularity and is a staple fixture on many racing series' calendars, Formula One included. It is also a regularly used testing venue, while the parkland remains open to the public - you can even find an outdoor municipal swimming pool in the grounds alongside the main straight...",
    source: "Monza, racingcircuits.info",
  },
  {
    name: "Portuguese GP - Algarve International Circuit",
    path: "Portuguese",
    description: "Commonly known as Portimão for the city in which it's based, Algarve International Circuit is one of Portugal's premier racing facilities. Twice the home of the Portuguese Grand Prix, the track has also hosted the 6 Hours of Portimão, numerous TCR events, and various other motorcycle, open wheel, and sports car races in that time. A lap of Portimão is marked by heavy elevation changes throughout its 4.653 km (2.891 mile) layout. These big slopes mix with a varied selection of both tight and sweeping turns to produce one of the most old-school feeling laps out of any circuit to be built in the 2000s.",
    source: "Algarve International Circuit, iracing.com",
  },
  {
    name: "Qatar GP - Lusail International Circuit",
    path: "Qatar",
    description: "The circuit features a 5.4-kilometer track that presents a sophisticated blend of medium and high-speed turns, including several left-handers favored by racers. The track's design effectively counters the desert sand with artificial grass borders, keeping the tarmac clear for consistent racing conditions. Notably, the circuit's main straight stretches over a kilometer, setting the stage for high adrenaline starts and overtakes. The addition of permanent outdoor lighting has enabled night racing, enhancing the circuit's versatility and experience both for attendees and television audiences.",
    source: "Lusail International Circuit, f1chronicle.com",
  },
  {
    name: "Austrian GP - Red Bull Ring",
    path: "Red-Bull-Ring",
    description: "Styria is home to one of the most modern race tracks in the world. The Red Bull Ring is characterized by a combination of fast straights and demanding corners. Embedded in the natural scenery, the course has significant differences in altitude, which leads to spectacular inclines (max. gradient 12%) and declines (max. gradient 9.3%). At the same time, the typography offers spectators an optimal view of large parts of the track - and thus of the racing action. [...] The Red Bull Ring is not only known for its impressive route, but also for the breathtaking backdrop of the Austrian Alps. This combination makes the race track so popular with drivers, teams and fans.",
    source: "RED BULL RING - FORMULA 1 CIRCUIT, redbullring.com",
  },
  {
    name: "Sao Paulo GP - Interlagos",
    path: "Sao-Paulo",
    description: "The circuit is known for its many inclines and formerly bumpy surface, which could take its toll on F1 cars because they have a very low ride height and little suspension travel. The races are therefore very tough on the car, and also physically tough on the drivers, especially since the circuit is anti-clockwise, where the centrifugal forces in the many hard left turns push the drivers' necks to the right, instead of left as in the majority of circuits on the F1 calendar. [...] Another reason why many drivers consider Interlagos interesting is that it was not built on flat terrain, but follows the ups and downs of hilly ground, which makes it harder to drive and demands more power from the car's engines.",
    source: "Autódromo José Carlos Pace, f1.fandom.com",
  },
  {
    name: "Saudi Arabian GP - Jeddah Corniche Circuit",
    path: "Saudi-Arabian",
    description: "The Jeddah Corniche Circuit is, you won't be surprised to hear, a temporary street circuit (albeit adorned with some permanent sections), located on the Corniche - a 30km coastal resort area of the ancient Saudi Arabian city of Jeddah. [...] Average speeds around the Jeddah Corniche Circuit are around 250km/h - quicker than those at Silverstone, and second on the 2021 calendar only to Monza - aka 'The Temple of Speed'. It is, quite simply, the fastest street circuit ever seen in Formula 1 - while the track also features the most corners on the calendar with 27, many of them quick, sinuous bends as the drivers wend their way along the Jeddah waterfront.",
    source: "Jeddah Corniche Circuit, formula1.com",
  },
  {
    name: "Chinese GP - Shanghai International Circuit",
    path: "Shanghai-International",
    description: "The track layout was inspired from the Chinese character shang, the first character in the name of the city Shanghai , meaning 'above' or 'ascend'. There's a unique start to the lap as the drivers fly into the ever-tightening Turns 1 and 2, before they dart left through 3 and 4. The super-high g force Turns 7 and 8 are loved by the drivers, while the circuit also features one of the longest straights on the calendar, the 1.2 km (0.7 mi) stretch that separates turns 13 and 14.",
    source: "Shanghai International Circuit, wikipedia.com",
  },
  {
    name: "British GP - Silverstone Circuit",
    path: "Silverstone",
    description: "Little did those laying the perimeter road to the RAF Silverstone airfield in 1942 know that they were setting down what would become one of the world's greatest race tracks. But, well, they were! The Silverstone circuit was first used for a proper motor race in 1947 - although sadly, a local sheep lost its life during the proceeding... [...]  Despite numerous layout changes over the years, Silverstone has always maintained its essential character as one of the fastest tracks on the F1 calendar, while historic corners like Maggotts, Becketts and Abbey provide some of the biggest challenges for racing drivers anywhere in the world.",
    source: "Silverstone Circuit, formula1.com",
  },
  {
    name: "Russian GP - Sochi Autodrom",
    path: "Sochi",
    description: "Designed by Hermann Tilke, the Sochi Autodrom is effectively a street circuit, evolving out of the internal roads of the park built for the city's 2014 Winter Olympics. [...] Looking at a map of the track, your eye can't help but be drawn to the epic Turn 3, a 750m constant-radius left-hander taking the drivers around the outside of the dramatic Poyushchiye fountain. The rest of the track is characterised by a series of 90-degree bends coupled to some rapid, flowing straights-that-aren't-straight.",
    source: "Russia - Sochi, formula1.com",
  },
  {
    name: "Belgium GP - Spa-Francorchamps",
    path: "Spa-Francorchamps",
    description: "The original, triangle-shaped track was built in 1921, with designers Jules de Thier and Henri Langlois van Ophem using public roads between the towns of Francorchamps, Malmedy, and Stavelot to create an amazing 14.9km circuit taking in the forests and rolling hills of the beautiful Ardennes region. The track was redeveloped in 1979, and although the new circuit is only half the original's length, it's still the longest on the current calendar at 7.004km. [...] Keep an eye on the thrilling Eau Rouge, arguably the most famous sequence of corners in the world, as the drivers flick left, right and then up the hill through Raidillon.",
    source: "Circuit de Spa-Francorchamps, formula1.com",
  },
  {
    name: "Japanese GP - Suzuka Circuit",
    path: "Suzuka",
    description: "In 1962. Soichiro Honda, whose car company you may have heard of, was a man with big ambitions. Seeking to turn Honda into an automotive powerhouse, he decided his company should have its own test track. Dutchman John Hugenholtz got the nod, and drew up the now-iconic 'crossover' Suzuka track - although original drawings saw the track pass over and under itself a full three times, which would have been sweet! [...] The high-speed track remains one of the ultimate driving challenges, with the snaking 'S' Curves, the two commitment-rewarding Degners and the white-knuckle ride of 130R all highlights in a series of highlights at what is one of F1's seminal tracks.",
    source: "Suzuka International Racing Course, formula1.com",
  },
  {
    name: "Abu Dhabi GP - Yas Marina Circuit",
    path: "Yas-Marina",
    description: "In 2006, plans were announced to develop Yas Island, located just to the east of Abu Dhabi, into a new tourist destination, with a major part of the plans centring around a 5.5km race track. The diggers rolled into what would become the Yas Marina Circuit in May 2007, with the project completed by October 2009. [...] The Hermann Tilke-designed track is dominated by its 1.2km straight between Turns 5 and 6 - which, with slow-speed corners marking its beginning and end, makes it a honeypot for overtaking moves. Other highlights include the tricky run through Turns 10 and 11 into 12, which forces the drivers to brake hard with bags of lateral load still on the car.",
    source: "Yas Marina Circuit, formula1.com",
  },
  {
    name: "Dutch GP - Circuit Zandvoort",
    path: "Zandvoort",
    description: "The link between Zandvoort and motorsport is taking us back to the late 1930s when motorsport aficionados decided to organise a competition in Zandvoort. The race in 1939 was held on a temporary street circuit. After its huge success, it was decided to build a permanent facility. [...] At a length of 4.3 kilometres, it ranks among the shorter circuits on the F1 calendar: hardly anywhere else, drivers zoom past the race fans that often! [...] The highly challenging circuit features 14 corners and will be fully upgraded to meet the highest standard whilst maintaining the unique character that makes Circuit Zandvoort stand out.",
    source: "Circuit Zandvoort, dutchgp.com",
  },
];
